name: Generate QR Code

on:
  push:
    branches: [ main ]

jobs:
  generate-qr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install segno

    - name: Generate QR code for repo
      run: |
        python - <<EOF
        import segno
        repo_url = "https://github.com/${{ github.repository }}"
        qr = segno.make_qr(repo_url)
        qr.save("qr_repo.png", scale=10, border=2, dark="#2F3961", light="#FFFFFF")
        EOF

    - name: Commit and push QR code
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add qr_repo.png
        git commit -m "Update QR code"
        git push
      continue-on-error: true
